name: CI PIPELINE

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint_build_test:
    name: Linting Building and Testing

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Use node ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Dependencies
        uses: npm ci

      - name: Lint Code
        uses: npm run lint

      - name: Build code
        uses: npm run build

      - name: Test Code
        uses: npm run test
